Rework `cup` capability
tolstoyevsky/gits pull request #11
Opened 2017-01-03 09:57 UTC by dshil

* No need to set end of line flag to false each time.
* Add test for corresponding capability.

2017-01-03 13:49 UTC, eugulixes requested changes

2017-01-03 13:49 UTC, eugulixes commented on gits/terminal.py
> +        position to the `p2` value.
You mentioned the `p1` and `p2` params, but we have only `mo`.

2017-01-03 13:49 UTC, eugulixes commented on gits/test/terminal_test.py
> +        # Check setting the `eol` (end of line) flag.
Vague. I think `Check reaching the end of the line.` is better. What do you think?

2017-01-04 10:30 UTC, dshil commented on gits/test/terminal_test.py
> +        # Check setting the `eol` (end of line) flag.
Sounds good.

2017-01-04 10:44 UTC, dshil commented on gits/terminal.py
> +        position to the `p2` value.
fxd

2017-01-04 12:19 UTC, eugulixes approved these changes

2017-01-04 14:05 UTC, eugulixes approved these changes

2017-01-04 14:08 UTC, merged